function out = krondelta_multi(basis,qnames,row_ind,col_ind)
out = all(...
    basis.qnums{row_ind,~ismember(basis.qnums.Properties.VariableNames,qnames)}==...
    basis.qnums{col_ind,~ismember(basis.qnums.Properties.VariableNames,qnames)},2);
end