function out = transition_dipole_case_aFC(r,c,p,T1q)

if nargin==4
    out = (-1).^(r.F-r.m_F) .* w3j(r.F,-r.m_F,1,p,c.F,c.m_F) ...
        .* (r.I==c.I) .* (-1).^(c.F+r.J+1+r.I) .* sqrt((2*r.F+1).*(2*c.F+1)) .* w6j(c.J,c.F,r.I,r.F,r.J,1) ...
        .* (-1).^(r.J-r.Omega) .* sqrt((2*r.J+1).*(2*c.J+1))...
        .* (w3j(r.J,-r.Omega,1,1,c.J,c.Omega).*T1q(1) ...
        + w3j(r.J,-r.Omega,1,0,c.J,c.Omega).*T1q(2) ...
        + w3j(r.J,-r.Omega,1,-1,c.J,c.Omega).*T1q(3));
else
    out = (-1).^(r.F-r.m_F) .* w3j(r.F,-r.m_F,1,p,c.F,c.m_F) ...
        .* (r.I==c.I) .* (-1).^(c.F+r.J+1+r.I) .* sqrt((2*r.F+1).*(2*c.F+1)) .* w6j(c.J,c.F,r.I,r.F,r.J,1) ...
        .* (-1).^(r.J-r.Omega) .* sqrt((2*r.J+1).*(2*c.J+1))...
        .* (w3j(r.J,-r.Omega,1,r.Omega-c.Omega,c.J,c.Omega));
end


if ismember('eta',r.Properties.VariableNames)
    boo = abs(r.eta-c.eta)==1;
    out = out.*boo;
end

end